### PR TITLE
Fix Lab 1 format issue

### PR DESCRIPTION
**Pull request by hickeyma**
Formatting in "Remote Host" sections is not aligned correctly and as a consequence the doc is rendered incorrectly.

### CODE REVIEW

**Comment by spzala** [comment]
lgtm but on formatting good idea to take care of couple of other things as well: 
1. `View the guestbook` and `Install the app as a Helm chart` should have colon (e.g. `View the guestbook:`) like how we have on top of the page for kubectl 
2. I wonder if there is an easy to align the following for both kubectl and Helm (if we can in an easier way, if not that's no problem.. just a thought):

    2. View the guestbook:
You can now play with the guestbook that you just created by opening it in a browser (it might take a few moments for the guestbook to come up).

**Comment by hickeyma** [comment]
@spzala Thank you for your review and comments. PR ready again for review.

**Comment by spzala** [comment]
The formatting lgtm, thanks for addressing my comments Martin!

**Comment by hickeyma** [comment]
@spzala Thank you for your review and merge.

**Pull request merged**
