### PR TITLE
Update review comments

### PR DESCRIPTION
**Pull request by hickeyma**
- Update of deck for TechTalk
- Review  on Monday 26th of November

### CODE REVIEW

**Comment by spzala** [comment]
Hi Martin, this looks great but few minor comments:
slide #2 : Can we remove 'everewhere' ? (I guess we don't need to be too explicit here - what do you think?) 
slide #5 : Let's put the link at the bottom of the slide as we did with other slides (e.g. slide #4)? 
slide #16 : Let's replace "Guestbook Chart Walkthrough" with "Guestbook Chart" (Since we decided not to do walk through as we have slide with screen capture later on in the presentation)? 
slide # 25 : "Get the history of upgrades and rollbacks" is in Italic so un-italic it to be consistent with other bullets.
Also great job with font consistency with this new template. Thanks!!

**Comment by hickeyma** [comment]
@spzala Thanks for the review and comments. Deck now updated.

> slide #2 : Can we remove 'everewhere' ? (I guess we don't need to be too explicit here - what do you think?)

I think it is better to leave the word 'everywhere' in. It helps specify the problem domain.

> slide #5 : Let's put the link at the bottom of the slide as we did with other slides (e.g. slide #4)?

Done.

> slide #16 : Let's replace "Guestbook Chart Walkthrough" with "Guestbook Chart" (Since we decided not to do walk through as we have slide with screen capture later on in the presentation)?

Done.

> slide # 25 : "Get the history of upgrades and rollbacks" is in Italic so un-italic it to be consistent with other bullets.

Done.

> Also great job with font consistency with this new template. Thanks!!

Not a bother. It needed some tidy up alright.

**Comment by spzala** [comment]
@hickeyma thanks and lgtm

**Comment by spzala** [comment]
@duglin can we merge this? Thanks!

**Comment by hickeyma** [comment]
@spzala and @duglin thanks

**Pull request merged**
